// AUTO-GENERATED by scripts/apply-domain.mjs — do not edit by hand.
// Active domain pack: okc-barber
import type { SeedData } from "./db.ts";
export const SEED: SeedData = {
  "settings": {
    "business_name": "Plaza District Barber Co.",
    "business_address": "1700 NW 16th St\nOklahoma City, OK 73106",
    "business_phone": "(405) 555-0142",
    "tax_rate": "0.08625",
    "receipt_footer": "Look sharp, OKC.\nWalk-ins welcome — Plaza District."
  },
  "catalog": [
    {
      "name": "Haircut",
      "category": "Haircuts",
      "price_cents": 3000,
      "color": null,
      "description": null,
      "taxable": 0
    },
    {
      "name": "Haircut & Beard",
      "category": "Haircuts",
      "price_cents": 4000,
      "color": null,
      "description": null,
      "taxable": 0
    },
    {
      "name": "Skin Fade",
      "category": "Haircuts",
      "price_cents": 3500,
      "color": null,
      "description": null,
      "taxable": 0
    },
    {
      "name": "Beard Trim",
      "category": "Beard & Shave",
      "price_cents": 1500,
      "color": null,
      "description": null,
      "taxable": 0
    },
    {
      "name": "Hot Towel Shave",
      "category": "Beard & Shave",
      "price_cents": 3000,
      "color": null,
      "description": null,
      "taxable": 0
    },
    {
      "name": "Kids Cut (12 & under)",
      "category": "Kids & Seniors",
      "price_cents": 2000,
      "color": null,
      "description": null,
      "taxable": 0
    },
    {
      "name": "Senior Cut",
      "category": "Kids & Seniors",
      "price_cents": 2000,
      "color": null,
      "description": null,
      "taxable": 0
    },
    {
      "name": "Line-up / Edge-up",
      "category": "Add-ons",
      "price_cents": 1000,
      "color": null,
      "description": null,
      "taxable": 0
    },
    {
      "name": "Pomade",
      "category": "Retail Products",
      "price_cents": 1800,
      "color": null,
      "description": null,
      "taxable": 1
    },
    {
      "name": "Beard Oil",
      "category": "Retail Products",
      "price_cents": 2200,
      "color": null,
      "description": null,
      "taxable": 1
    }
  ]
};
