// AUTO-GENERATED by scripts/apply-domain.mjs — do not edit by hand.
// Active domain pack: okc-barber
export const APP_NAME = "Plaza District Barber Co.";
export const REGISTER_LABEL = "Checkout";
export const CATEGORIES: string[] = ["Haircuts","Beard & Shave","Kids & Seniors","Add-ons","Retail Products","Fees"];
export const COLORS: string[] = ["#0f172a","#b45309","#334155","#92400e","#475569","#a16207"];
