import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import App from "./App";
import "./index.css";
// Per-domain brand tokens (generated by scripts/apply-domain.mjs). Imported AFTER index.css and
// unlayered, so its :root values override the @layer base fallback.
import "./brand.generated.css";

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
