#!/usr/bin/env node
// apply-domain.mjs — THE SELECTOR. "One core, switchable packs."
//
// Reads the active domain (argv or kit.config.json), validates its pack against the pack schema,
// and materializes every per-domain file the core imports. The core SOURCE never changes between
// domains — only these generated files do:
//
//   backend/seed.generated.ts          settings defaults + seed catalog (taxable as 0/1)
//   backend/logo.ts                    embedded logo data URI + brand colors (for receipts)
//   renderer/src/catalog-meta.ts       CATEGORIES, COLORS, APP_NAME, REGISTER_LABEL
//   renderer/src/brand.generated.css   --brand-* CSS vars
//   renderer/src/assets/active-logo.svg  header logo (Vite asset)
//
// Usage:  node scripts/apply-domain.mjs [pack-name]

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { validate } from "./lib/jsonschema.mjs";
import { buildLogo } from "./lib/logo.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const readJson = (p) => JSON.parse(readFileSync(join(ROOT, p), "utf8"));

const config = readJson("kit.config.json");
const packName = process.argv[2] || config.activeDomain;
const domainsDir = config.domainsDir || "domains";
const packDir = join(ROOT, domainsDir, packName);
const packPath = join(packDir, "pack.json");

if (!existsSync(packPath)) {
  console.error(`✗ no pack at ${domainsDir}/${packName}/pack.json`);
  process.exit(1);
}

const pack = JSON.parse(readFileSync(packPath, "utf8"));
const schema = readJson(`${domainsDir}/_schema/pack.schema.json`);
const errs = validate(pack, schema, packName);
if (pack.pack !== packName) errs.push(`'pack' is '${pack.pack}', expected '${packName}'`);
if (errs.length) {
  console.error(`✗ pack ${packName} is invalid:`);
  for (const e of errs) console.error(`  - ${e}`);
  process.exit(1);
}

const GEN = "// AUTO-GENERATED by scripts/apply-domain.mjs — do not edit by hand.\n" +
  `// Active domain pack: ${packName}\n`;

// ── backend/seed.generated.ts ──
const seed = {
  settings: pack.settings,
  catalog: pack.seedCatalog.map((i) => ({
    name: i.name,
    category: i.category,
    price_cents: i.price_cents,
    color: i.color ?? null,
    description: i.description ?? null,
    taxable: i.taxable ? 1 : 0,
  })),
};
writeFileSync(
  join(ROOT, "backend/seed.generated.ts"),
  `${GEN}import type { SeedData } from "./db.ts";\nexport const SEED: SeedData = ${JSON.stringify(seed, null, 2)};\n`,
);

// ── backend/logo.ts + renderer header asset ──
const logoFile = pack.logo ? join(packDir, pack.logo) : undefined;
const { dataUri, svg } = buildLogo({ appName: pack.appName, brand: pack.brand, file: logoFile });
writeFileSync(
  join(ROOT, "backend/logo.ts"),
  `${GEN}export const LOGO_DATA_URI = ${JSON.stringify(dataUri)};\n` +
  `export const BRAND = ${JSON.stringify(pack.brand)};\n`,
);
mkdirSync(join(ROOT, "renderer/src/assets"), { recursive: true });
writeFileSync(join(ROOT, "renderer/src/assets/active-logo.svg"), svg);

// ── renderer/src/catalog-meta.ts ──
const colors = pack.colors ?? ["#2563eb", "#16a34a", "#d97706", "#dc2626", "#7c3aed", "#0891b2"];
writeFileSync(
  join(ROOT, "renderer/src/catalog-meta.ts"),
  `${GEN}export const APP_NAME = ${JSON.stringify(pack.appName)};\n` +
  `export const REGISTER_LABEL = ${JSON.stringify(pack.registerLabel ?? "Register")};\n` +
  `export const CATEGORIES: string[] = ${JSON.stringify(pack.categories)};\n` +
  `export const COLORS: string[] = ${JSON.stringify(colors)};\n`,
);

// ── renderer/src/brand.generated.css ──
writeFileSync(
  join(ROOT, "renderer/src/brand.generated.css"),
  `/* AUTO-GENERATED by scripts/apply-domain.mjs (${packName}) */\n` +
  `:root {\n  --brand-from: ${pack.brand.from};\n  --brand-via: ${pack.brand.via};\n  --brand-to: ${pack.brand.to};\n}\n`,
);

console.log(`✓ applied domain '${packName}' → ${pack.appName}`);
console.log(`  seed: ${seed.catalog.length} items (${seed.catalog.filter((i) => i.taxable).length} taxable, ${seed.catalog.filter((i) => !i.taxable).length} exempt)`);
console.log(`  brand: ${pack.brand.from} → ${pack.brand.to}`);
