#!/usr/bin/env node
// embed-logo.mjs — bake a real image file into backend/logo.ts as a base64 data URI and copy
// it to the renderer assets. The backend ships as a single `deno compile` exe with no files on
// disk, so the logo MUST be inlined (constraint: embed-binary-assets).
//
// Most domains use the synthesized wordmark from scripts/apply-domain.mjs and never need this.
// Use it when a pack provides a real logo:  node scripts/embed-logo.mjs <image> [brandFrom brandVia brandTo]
//
// Usage example:  node scripts/embed-logo.mjs domains/okc-salon/logo.png "#831843" "#be185d" "#f9a8d4"

import { writeFileSync, copyFileSync, existsSync } from "node:fs";
import { join, dirname, extname } from "node:path";
import { fileURLToPath } from "node:url";
import { buildLogo } from "./lib/logo.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const [file, from = "#6d28d9", via = "#7c3aed", to = "#a78bfa"] = process.argv.slice(2);

if (!file || !existsSync(file)) {
  console.error("usage: node scripts/embed-logo.mjs <image-file> [from via to]");
  process.exit(1);
}

const brand = { from, via, to };
const { dataUri, svg } = buildLogo({ appName: "Logo", brand, file });
writeFileSync(
  join(ROOT, "backend/logo.ts"),
  `// AUTO-GENERATED by scripts/embed-logo.mjs — do not edit by hand.\n` +
  `export const LOGO_DATA_URI = ${JSON.stringify(dataUri)};\n` +
  `export const BRAND = ${JSON.stringify(brand)};\n`,
);
// Mirror the asset to the renderer so the header can `import logoUrl from './assets/...'`.
const ext = extname(file).toLowerCase();
if (ext === ".svg" || !svg) {
  copyFileSync(file, join(ROOT, `renderer/src/assets/active-logo${ext}`));
} else {
  writeFileSync(join(ROOT, "renderer/src/assets/active-logo.svg"), svg);
}
console.log(`✓ embedded ${file} into backend/logo.ts`);
